### PR TITLE
Copy jlab iframe cursor css hack

### LINKED ISSUE #2: Unable to reduce width of jitsi window
Jitsi windows seems to easily be able to grow in width but does not respond to minimizing the window.

### PR DESCRIPTION
**Pull request by bollwyvl**
this fixes #2 by copying the jlab css hack:
https://github.com/jupyterlab/jupyterlab/blob/v2.1.5/packages/apputils/style/iframe.css#L15-L32

### CODE REVIEW

**Comment by bollwyvl** [comment]
if somebody (e.g. @costrouc @goanpeca @yuvipanda) could take a spin on binder... 

https://mybinder.org/v2/gh/bollwyvl/jupyter-videochat/fix-iframe-dragging?urlpath=lab

**Comment by goanpeca** [comment]
Woot @bollwyvl ! Testing now!

**Comment by goanpeca** [comment]
```
Waiting for build to start...
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-1j6alj4x.log

         jlpm


         jlpm build


         jupyter labextension link .


ERROR 1 jupyter labextension link .
Removing intermediate container 1bb162bd2799
The command '/bin/sh -c ./binder/postBuild' returned a non-zero code: 1
```  💩

**Comment by bollwyvl** [comment]
eek! looking into it!

**Comment by yuvipanda** [comment]
Yeah, I spent a day tring to get binder to work and gave up. and use github.com/yuvipanda/jupyter-videochat-demo for demos. I was surprised, since it was just off the lab cookiecutter

**Comment by bollwyvl** [comment]
Screenshot from 2020-07-03 12-25-02

**Comment by yuvipanda** [comment]
woop woop, Thanks @bollwyvl. Looking amazing as always!!! Love the lighting <3

**Comment by goanpeca** [comment]
Dude @bollwyvl you ara da man!

**Pull request merged**
