### PR TITLE
Update for JupyterLab 3, Router, Settings, etc.

### LINKED ISSUE #3: Consider switching to main area widget
We like to keep the side panel widgets for things that are skinny...

Since this might wanna be a bit larger, if you are trying to see someone's notebook, it might be nice to have this also be able to be a main area widget with a launcher icon.

cc @isabela-pf

### LINKED ISSUE #7: Add lab router link?
It would be cool to be able to support links like:

```
https://mybinder.org/v2/gh/yuvipanda/jupyter-videochat/master?urlpath=lab/chat/{:room-name}[/{:file}]
```

That would:
- do the normal binder thing
- open the named chat
- (optionally) open a file

This would make sending out a link to join a follow-along-at-home demo a one-click kind of thing.

### LINKED ISSUE #12: JupyterLab 3.0 support
Currently this doesn't work with JupyterLab 3.0. It should.

### PR DESCRIPTION
**Pull request by bollwyvl**
Sorry for the monster PR. 

[Binder](https://mybinder.org/v2/gh/bollwyvl/jupyter-videochat/master?urlpath=lab%3Fjvc%3Dfoo)

References:
- fixes #7
- fixes #12
- fixes #3

Changes:
- supports JupyterLab
  - this eschews `jupyter-packaging` and `build-system` with some simpler stuff... 
    - i don't like `npm` stuff running inside of `pip install`, much less `webpack`
- reworks the package metadata
  - the only version number is `package.json/version`
- reworks CI
  - build the `whl`, `tar.gz` and `tgz` in one linux job, add a `SHA256SUM` file
  - test against a matrix vs installing the `.whl` or `.tar.gz`
  - still building the npm tarball because...
- hoists the Meet instance to a new `VideoChatManager` exposed as the token that other plugins can use in `activate`
  - this will allow other extensions to do... things with the current Meeting. Not sure what, but i'm excited about: 
    - being able to replace the chat with real (markdown) cells
    - breakout rooms (#5)
- adds settings for
  - user display name and email
  - configOverwrite (adds `disableThirdPartyRequests` to defaults)
  - interfaceConfigOverwrite (also hides the google/office 365 extension banner)
  - hiding public room UI (true by default)
- allows for creating public rooms
- reworks the DOM structure some, especially on the room list
  - tries to use more accessible/semantic HTML, remove lots of classes
  - some icons
- loads `external_api.js` directly from the jitsi domain (via gross `<script>` injection, but what can you do) instead of bundling

### CODE REVIEW

**Review by yuvipanda — COMMENTED** [review]
Couple questions on compatibility between notebook & jupyter_server packages. But otherwise - I don't think I've the capability to CR the labextension, so I'll just merge it since you're cool & awesome :)

**Comment by bollwyvl** [comment]
> questions on compatibility between notebook & jupyter_server packages

What's the flavor of concern? The `nbclassic` route works... but I don't know for how long. I could see issues arising prior to the hard cut at lab 4.x, but haven't been keeping track of the various lifecycle pieces. 

A thing I'd _really_ like to see is this working with `voila` (likely as a separate package), which is already `jupyter_server`-only.

As for integration with other UIs... I don't think the design constraints of `jupyterlab-classic` lend itself very well to this extension, as a dialog would be extremely unsatisfying, and if you start slamming more dom in the page... that might be resizable... and tabbed... well, sure sound like Lab at that point. 

>  CR the labextension

Yeah, we had some events to run and needed some of the capability, so that initial PR kinda just kept going. Of course, shame on me for not having added better tests, but Always Be Demoing... 

A follow-on could raise the browser testing game some... it would crack me up to have different CI bots talking to each other on Jitsi during CI

```
LINUX 3.9:     YO, WINDOWS, YOUR FILESYSTEM SO FAT, IT NEEDS 128 BITS
WINDOWS 3.6:   *CRIES*
MACOS 3.9:     BURN.
```

> just merge it

cool, appreciated. I'll do another look over it, and re-request review... doing the binder shakedown i noticed some stuff, as it's the only hub-like-thing i have to test open source stuff. If you had any notes from it (not) working in your required hub setup, that would be rad. You can grab the tarballs from the dist asset.

**Comment by bollwyvl** [comment]
Alright, there are still some lingering issues with restoring a _particular_ video chat after refreshing the browser... I think i messed up the commands somehow. Otherwise, shook down everything I found that was bothering me. I guess give it a spin and let me know what's missing from a functionality perspective. While working on it, had some ideas I'll hoist to follow-on issues.

**Comment by bollwyvl** [comment]
@yuvipanda thoughts?

**Comment by yuvipanda** [comment]
@bollwyvl I've hit the merge button :D Will you be able to do appropriate releases? <3

**Comment by bollwyvl** [comment]
:heart_eyes_cat: on it. I'll start a release ticket, and start shaking it down.

**Pull request merged**
